### ISSUE TITLE
Trying to install gem results in YAML error

### ISSUE THREAD

**Issue by contentfree** [kares/session_off#1]
Specifically, trying to install session_off 0.3 with rubygems 1.8.10 results in: "Psych::SyntaxError: couldn't parse YAML at line 46 column 13"

**Comment by kares** [comment]
Reproduced on ruby 1.9.2 - caused by YAML line: 

```
description: `session :off, :only => :foo, :if => Proc.new { |req| req.params[:bar] }`
```

Will release a **0.3.1** version with a fix.
Thank you for reporting this !
