### ISSUE TITLE
Migrating to Rails 4 break session_off

### ISSUE THREAD

**Issue by Electron-libre** [kares/session_off#3]
I used session_off with a Rails 3.2 App in order to disable session for API clients.

I am migrating to Rails 4 but it seems that request.session_options is not a hash anymore, then does not implement #merge!

Here the backtrace :  https://gist.github.com/Electron-libre/5927912

I had a look to https://github.com/rails/rails/blob/v4.0.0/actionpack/lib/action_dispatch/request/session.rb

and past changes to the session options, and can't even explain why it has worked before, since there were no changes from rails 3.2 to Option class.

But yout test still pass with rails 4 emulation so digged a bit in runtime : 
https://gist.github.com/Electron-libre/5928099

It seems that request.session_option is not a hash anymore.

Before to submit a fix, I'd like you opinion , can you reproduce this bug ?

Do you know what has changed in rails API ? It seem that this change is undocumented or these objects where not supposed to be override.

**Comment by Electron-libre** [comment]
Ok I've got a fix , I send you pull request.
Anyway I am running out of time to fix the missleading test result for Rails 4 
see : https://gist.github.com/Electron-libre/5929876

Tests passes but, they should not, since it does not work with Rails/Rack server.
Maybe your stubs does only take care of Rails 3.2 session_option Hash.

If I have time later I'll have a look, but if you have clue I'll save some precious time ;)

**Comment by kares** [comment]
Thanks Cedric, will look into reproducing this on **4.0** and try to come up with a release ...
